#Visualising
data=VanNuys
date=seq(as.Date("1973-03-31"),as.Date("2015-05-31"),by="days")
day=seq(1,15402)
wind=as.numeric(VanNuys[,1])
ffwi=as.numeric(VanNuys[,2])
plot(date,wind)
plot(date,ffwi)
wind_nona=wind[!is.na(wind)]
ffwi_nona=ffwi[!is.na(ffwi)]
acf(wind_nona)
acf(ffwi_nona)
month=months(date)
